version: '3'
services:
  postgres:
    build: database/PostgreSQL
    image: factory-postgres-database:1.0.0
    ports:
      - "5431:5432"


  mongo:
    build: database/MongoDB
    image: factory-mongo-database:1.0.0
    ports:
      - "27016:27017"


  backend:
    build: backend
    image: factory-backend:1.0.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/factory_db
      - SPRING_DATASOURCE_USERNAME=factory_user
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"


  frontend:
    build: frontend
    image: factory-frontend:1.0.0
    ports:
      - "3000:80"