version: '3'
services:
  postgres:
    build: database
    image: factory-database:1.0.0
    ports:
      - "5432:5432"


  backend:
    build: backend
    image: factory-backend:1.0.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/factory_db
      - SPRING_DATASOURCE_USERNAME=factory_user
      - SPRING_DATASOURCE_PASSWORD=admin
    ports:
      - "8080:8080"


  frontend:
    build: frontend
    image: factory-frontend:1.0.0
    ports:
      - "3000:80"