spring:
  application:
    name: factory-database-service
  datasource:
    url: jdbc:postgresql://localhost:5432/factory_db
    username: factory_user
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    mongodb:
      uri: mongodb://localhost:27017/factory_db
      username: factory_user
      password: admin
server:
  port: 8080